[[Shaders]]
flags = 0
fragment = 'shaders/cubemap.frag'
guid = 103
vertex = 'shaders/cubemap.vert'

[[Shaders]]
flags = 0
fragment = 'shaders/simpleDepthShader.frag'
guid = 104
vertex = 'shaders/simpleDepthShader.vert'

[[Shaders]]
flags = 0
fragment = 'shaders/shadowDebug.frag'
guid = 105
vertex = 'shaders/shadowDebug.vert'

[[Shaders]]
flags = 0
fragment = 'shaders/HDRBloom.frag'
guid = 106
vertex = 'shaders/default.vert'

[[Shaders]]
flags = 0
fragment = 'shaders/brdf.frag'
guid = 107
vertex = 'shaders/default.vert'

[[Shaders]]
flags = 0
fragment = 'shaders/prefilter.frag'
guid = 108
vertex = 'shaders/prefilter.vert'

[[Shaders]]
flags = 0
fragment = 'shaders/downSample.frag'
guid = 109
vertex = 'shaders/default.vert'

[[Shaders]]
flags = 0
fragment = 'shaders/upSample.frag'
guid = 110
vertex = 'shaders/default.vert'

[[Shaders]]
flags = 0
fragment = 'shaders/irradiance.frag'
guid = 111
vertex = 'shaders/irradiance.vert'

[[Shaders]]
flags = 1
fragment = 'shaders/lineRenderer.frag'
guid = 112
vertex = 'shaders/lineRenderer.vert'

[[Shaders]]
flags = 11
fragment = 'shaders/superDuper.frag'
guid = 113
vertex = 'shaders/superDuper.vert'

[Camera]
fov = 60.0
position = [ 0.0, 1.5, 0.0 ]
rotation = [ -90.0, -89.0 ]

SceneObjects = []