[[Shaders]]
flags = 3
fragment = 'shaders/litNormal.frag'
guid = 101
vertex = 'shaders/litNormal.vert'

[[Shaders]]
flags = 3
fragment = 'shaders/lit.frag'
guid = 102
vertex = 'shaders/lit.vert'

[[Shaders]]
flags = 1
fragment = 'shaders/lightCube.frag'
guid = 103
vertex = 'shaders/lightCube.vert'

[[Shaders]]
flags = 0
fragment = 'shaders/cubemap.frag'
guid = 104
vertex = 'shaders/cubemap.vert'

[[Shaders]]
flags = 4
fragment = 'shaders/animate.frag'
guid = 105
vertex = 'shaders/animate.vert'

[[Shaders]]
flags = 3
fragment = 'shaders/pbr.frag'
guid = 106
vertex = 'shaders/pbr.vert'

[[Shaders]]
flags = 0
fragment = 'shaders/framebuffer.frag'
guid = 107
vertex = 'shaders/framebuffer.vert'

[[Shaders]]
flags = 0
fragment = 'shaders/simpleDepthShader.frag'
guid = 108
vertex = 'shaders/simpleDepthShader.vert'

[[Shaders]]
flags = 3
fragment = 'shaders/shadowMapping.frag'
guid = 109
vertex = 'shaders/shadowMapping.vert'

[[Shaders]]
flags = 0
fragment = 'shaders/shadowDebug.frag'
guid = 110
vertex = 'shaders/shadowDebug.vert'

[[Shaders]]
flags = 1
fragment = 'shaders/simpleTextured.frag'
guid = 111
vertex = 'shaders/simpleTextured.vert'

[[Shaders]]
flags = 3
fragment = 'shaders/superShader.frag'
guid = 112
vertex = 'shaders/superShader.vert'

[[Shaders]]
flags = 1
fragment = 'shaders/simpleTextured.frag'
guid = 111
vertex = 'shaders/simpleTextured.vert'

[Camera]
fov = 60.0
position = [ -0.9166626930236816, 0.936103880405426, 3.9778590202331543 ]
rotation = [ -87.0, -20.799999237060547 ]

[[SceneObjects]]
hasRenderer = true
name = 'Unnamed Scene Object'

[[SceneObjects]]
hasRenderer = true
name = 'Unnamed Scene Object'

[[SceneObjects]]
hasRenderer = true
name = 'Unnamed Scene Object'

[[SceneObjects]]
hasRenderer = true
name = 'Unnamed Scene Object'

[[SceneObjects]]
hasRenderer = true
name = 'Unnamed Scene Object'

[[SceneObjects]]
hasRenderer = true
name = 'Unnamed Scene Object'

[[SceneObjects]]
hasRenderer = true
name = 'Unnamed Scene Object'